#!/bin/sh

if [ -f /etc/init/ssh.conf ]; then
    if [ -e /etc/init/ssh.conf.override ]; then
        echo "sshd-enable \"Enable SSH server\""
        exit 0
    fi
elif [ -f /lib/systemd/system/ssh.service ]; then
    if [ ! -e /etc/systemd/system/sshd.service ]; then
        echo "sshd-enable \"Enable SSH server\""
        exit 0
    fi
else
    # No SSH detected
    exit 0
fi

echo "sshd-disable \"Disable SSH server\""
echo "sshd-permit-root \"Permit root login via SSH $(cat /etc/ssh/sshd_config  | grep '^PermitRootLogin' | cut -d ' ' -f 2)\""

