#!/bin/bash
cat << EOF > /etc/network/interfaces
# Reset by Butterknife
auto lo
iface lo inet loopback

# Use /etc/network/interfaces.d/blah or NetworkManager instead
source-directory interfaces.d
EOF

