#!/bin/bash

if [ ! -x /usr/bin/puppet ]; then
    echo "Puppet not installed, skipping Puppet agent state persistence"
    exit 0
fi

mkdir -p /var/lib/butterknife/persistent/puppet/ssl/certs/

if [ -e /var/lib/puppet/ssl/certs/ca.pem ]; then
    echo "Copying Puppet CA certificate ..."
    cp /var/lib/puppet/ssl/certs/ca.pem /var/lib/butterknife/persistent/puppet/ssl/certs/ca.pem
fi

# Change permissions
chown puppet:puppet /var/lib/butterknife/persistent/puppet
chmod 750 /var/lib/butterknife/persistent/puppet

# Substitute /var/lib/puppet with symlink to /var/lib/butterknife/persistent/puppet
rm -Rf /var/lib/puppet
ln -s /var/lib/butterknife/persistent/puppet /var/lib/puppet

# Remove lock
puppet agent --enable

# Enable service
sed -i -e 's/^START=.*/START=yes/' /etc/default/puppet
rm -f /etc/init/puppet.override
update-rc.d puppet enable
