#!/bin/bash

if [ -d /var/butterknife/persistent ]; then
    if [ -e /var/butterknife/persistent/hostname ]; then
        butterknife-change-hostname $(cat /var/butterknife/persistent/hostname)
        exit 0
    fi
fi

# This will be run at every boot anyway until hostname is customized
butterknife-generate-hostname

