#!/bin/bash


while :
do

    # Exit menu with cancel
    set -e

    action=$(dialog --menu "Deployment is almost finished, what next?" 0 0 0 \
        mbr "Install bootloader and reboot" \
        hostname "Change hostname $(cat /etc/hostname)" \
        domain "Join domain" \
        useradd "Create local user" \
        shell "Drop to instance shell" \
        2>&1 >$(tty))

    clear

    set +e

    case $action in
        mbr)
            grub-install $BUTTERKNIFE_DISK
            exit 0
        ;;
        hostname)
            butterknife-change-hostname
        ;;
        domain)
            butterknife-join-domain
            read -p "Press [Enter] to continue..."
        ;;
        useradd)
            butterknife-create-local-user
            read -p "Press [Enter] to continue..."
        ;;
        shell)
            bash
        ;;
    esac
done

