#!/bin/sh

# Read-write permissions to administrator and read-only to domain users
mkdir -p /srv/media
chown root:1000513 /srv/media
chmod 775 /srv/media

cat <<EOF >> /etc/samba/smb.conf

[media]
path=/srv/media
writable=yes
EOF

# Enable NetBIOS
systemctl unmask nmbd

# Enable SMB server
systemctl unmask smbd
