#!/bin/sh

set -e

if [ -z $1 ]; then
    if [ -e /var/lib/butterknife/persistent/hostname ]; then
        CURRENT=$(cat /var/lib/butterknife/persistent/hostname)
    else
        CURRENT=$(cat /etc/hostname)
    fi
    NEW=$(dialog --max-input 15 --inputbox "Enter hostname" 0 0 "$CURRENT" 2>&1 >$(tty))
else
    NEW=$1
fi

if [ -d /var/lib/butterknife/persistent ]; then
    echo $NEW > /var/lib/butterknife/persistent/hostname
fi

sed -i -e "s/^PRETTY_HOSTNAME=.*/PRETTY_HOSTNAME=$NEW/" /etc/machine-info
echo $NEW > /etc/hostname
sed -i -e "s/127\.0\.1\.1 .*$/127.0.1.1 $NEW/g" /etc/hosts
hostname -F /etc/hostname
