#!/bin/bash

if [ $UID -ne 0 ]; then
  echo 'Run as root with sudo!'
  exit 255
fi

set -e

GIVEN_NAME=$(dialog --inputbox "Enter given name" 0 0 2>&1 >$(tty))
SURNAME=$(dialog --inputbox "Enter surname" 0 0 2>&1 >$(tty))
USERNAME=$(dialog --inputbox "Enter username" 0 0 $(echo $GIVEN_NAME | tr '[:upper:]' '[:lower:]') 2>&1 >$(tty))

clear

adduser --gecos "$GIVEN_NAME $SURNAME,,," $USERNAME --disabled-password
chmod 0700 /home/$USERNAME

while :
do
    set -e
    PASSWORD=$(dialog --insecure --passwordbox "Enter password for $USERNAME" 0 0 2>&1 >$(tty))
    clear

    set +e
    echo -en "$PASSWORD\n$PASSWORD\n" | passwd $USERNAME
    if [ $? -eq 0 ]; then
        break
    fi
done

gpasswd -a $USERNAME adm
[ -x /usr/bin/sudo      ] && gpasswd -a $USERNAME sudo
[ -x /usr/sbin/cupsd    ] && gpasswd -a $USERNAME lpadmin
[ -x /usr/sbin/libvirtd ] && gpasswd -a $USERNAME libvirtd
